name = "ImPlot"
uuid = "e8efc688-5342-4ad4-b4ba-9025a731b363"
authors = ["Wiktor Phillips <wsphillips@gmail.com>"]
version = "0.1.1"

[deps]
CEnum = "fa961155-64e5-5f13-b03f-caf6b980ea82"
CImGui = "5d785b6c-b76f-510e-a07c-3070796c7e87"
CImPlot_jll = "278f1f02-c5a0-563f-9174-e8b244dda450"

[compat]
CEnum = "0.4.0"
CImGui = "~1.79.0"
CImPlot_jll = "0.8.0"
julia = "1.3"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
